name: sahai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.2.18
  cupertino_icons: ^1.0.6
  firebase_core: ^2.7.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  google_fonts: ^6.2.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.6.0
  provider: ^6.1.0
  cloud_firestore: ^4.7.0
  speech_to_text: ^6.1.0
  highlight_text: ^1.7.0
  avatar_glow: ^2.0.1
  permission_handler: ^10.3.0
  lottie: ^2.1.0
  vibration: ^1.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/animation.mp4