// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDda8XLjQjse8yF0p8-CwCv-JkTEz-nQQ0',
    appId: '1:659707782919:web:665bbb7c94632701dc47a2',
    messagingSenderId: '659707782919',
    projectId: 'pesu-chatbot-393ee',
    authDomain: 'pesu-chatbot-393ee.firebaseapp.com',
    storageBucket: 'pesu-chatbot-393ee.appspot.com',
    measurementId: 'G-8M4H1TCBN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEpkqqio1GM4XR92hMnF3zZXh8xIenlFk',
    appId: '1:659707782919:android:66d777c6fa34b528dc47a2',
    messagingSenderId: '659707782919',
    projectId: 'pesu-chatbot-393ee',
    storageBucket: 'pesu-chatbot-393ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9fYk7yD8uSdyfS2lUxsTwziCFQSRLf00',
    appId: '1:659707782919:ios:f087d5c59f893327dc47a2',
    messagingSenderId: '659707782919',
    projectId: 'pesu-chatbot-393ee',
    storageBucket: 'pesu-chatbot-393ee.appspot.com',
    iosBundleId: 'com.example.sahai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9fYk7yD8uSdyfS2lUxsTwziCFQSRLf00',
    appId: '1:659707782919:ios:f363eaabd8dee748dc47a2',
    messagingSenderId: '659707782919',
    projectId: 'pesu-chatbot-393ee',
    storageBucket: 'pesu-chatbot-393ee.appspot.com',
    iosBundleId: 'com.example.sahai.RunnerTests',
  );
}
